version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: payment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: paymentdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 